stages:
  setup_dvc_remote:
    # This stage configures the DVC Azure remote at runtime using the
    # AZURE_STORAGE_CONNECTION_STRING environment variable (provided by
    # GitHub Actions secrets). It runs before other stages so CI can
    # authenticate and pull/push cache. When the env var is not set,
    # the command is a no-op.
    cmd: >
      bash -lc 'if [ -n "$AZURE_STORAGE_CONNECTION_STRING" ]; then
      dvc remote modify --local myremote connection_string "$AZURE_STORAGE_CONNECTION_STRING"
      else
      echo "AZURE_STORAGE_CONNECTION_STRING not set, skipping remote config"
      fi'

  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/indian_restaurant_waste_dataset.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv


  data_preprocessing:
    cmd: python src/data_processing.py
    deps:
      - src/data_processing.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - data/processed/train_preprocessed.csv
      - data/processed/test_preprocessed.csv


  feature_eng:
    cmd: python src/feature_eng.py
    deps:
      - src/feature_eng.py
      - data/processed/train_preprocessed.csv
      - data/processed/test_preprocessed.csv
    outs:
      - data/processed/train_fe.csv
      - data/processed/test_fe.csv

  model_train:
    cmd: python src/model_train.py
    deps:
      - src/model_train.py
      - data/processed/train_fe.csv
    outs:
      - models/rf_food_waste_model.pkl
      - models/xgb_food_waste_model.pkl
      - models/lr_food_waste_model.pkl

  model_eval:
    cmd: python src/model_eval.py
    deps:
      - src/model_eval.py
      - data/processed/test_fe.csv
      - models/rf_food_waste_model.pkl
      - models/xgb_food_waste_model.pkl
      - models/lr_food_waste_model.pkl
    outs:
      - metrics/metrics.txt
      - metrics/metrics.json
